pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                sh 'pwd'
            }
        }

    //     stage('Build Image') {
    //         steps {
    //             sh '''
    //                cd Cat && docker build -t grace1676/cat:JR10 .
    //                cd ../helloworld && docker build -t grace1676/helloworld:JR10 .
    //                cd ../web-nginx && docker build -t grace1676/mynginx:JR10 .
    //                docker tag grace1676/cat:JR10 grace1676/cat:latest
    //                docker tag grace1676/helloworld:JR10 grace1676/helloworld:latest
    //                docker tag grace1676/mynginx:JR10 grace1676/mynginx:latest
    //                docker images
	// 	        '''
    //         }
    //     }

    //     stage('Push Image') {
    //         steps {
    //             withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'PSWD', usernameVariable: 'USER')]) {
    //                 sh """                        
    //                     docker login -u $USER -p $PSWD
    //                     for img in grace1676/cat:JR10 grace1676/cat:latest grace1676/helloworld:JR10 grace1676/helloworld:latest \
    //                            grace1676/mynginx:JR10 grace1676/mynginx:latest; \
    //                     do docker push \$img; done;
    //                 """
    //             }

    //         }
    //     }

        // stage('Deploy Service') {
        //     steps {
        //         sh '''
        //             docker-compose down
        //             docker-compose up -d
        //             docker-compose ps
        //         '''
        //     }
        // }

    }
}
