name: Docker Image CI

on:
   workflow_dispatch
#  push:
#    branches: [ "feature/cicd" ]
#  pull_request:
#    branches: [ "master" ]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        cd Cat && docker build . -t grace1676/cat:action10
        cd ../helloworld && docker build . -t grace1676/helloworld:action10
        cd ../web-nginx && docker build . -t grace1676/nginx:action10
        
    - name: Upload the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push grace1676/cat:action10
        docker push grace1676/helloworld:action10
        docker push grace1676/nginx:action10

    - name: SSH to Remote Server and Run docker-compose
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 20.5.65.179
        username: grace
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22      
        script: |
          echo "Running command on remote server"
          cd ~/WK2_Docker
          git pull
          echo Grace234567 | sudo -S docker-compose down
          echo Grace234567 | sudo -S  docker-compose up -d
          echo Grace234567 | sudo -S  docker-compose ps
        
     
